project:
  type: website
  output-dir: docs
  preview: 
    port: 5240
    browser: true
    
execute:
  freeze: auto

website:
  title: "Functional Programming in R"
  navbar:
    left:
      - href: index.qmd
        text: Labs
      # - href: lecture_notes.qmd
      #   text: Lecture Notes
  back-to-top-navigation: true

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    fontsize: 12pt
    page-layout: full
    link-external-newwindow: true



